build:
	docker build -t notify:latest .

run: build
	# Make sure you ran awsume for your account
	docker run \
	-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
	-e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
	-p 9000:8080 \
	--rm \
	--name notify \
	notify:latest

test:
  curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"message":"body-test","subject":"sub-test"}'

clean:
	docker rm notify

invoke:
  aws lambda invoke --function-name notify --cli-binary-format raw-in-base64-out --payload '{"message":"test","subject":"test"}' /dev/null