build:
	docker build -t emailer:latest .

run: build
	# Make sure you ran awsume for your account
	docker run \
		-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
		-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
		-e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
		-p 9000:8080 \
		--rm \
    --name emailer \
		emailer:latest

test:
  curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}'

clean:
	docker rm emailer
