build:
  docker build -t scraper .

run: build
  docker run \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
  --env-file ./.env \
  scraper

# docker login no longer needed with ecr cred helper
# aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 919759177803.dkr.ecr.us-east-1.amazonaws.com
publish:
  docker build -t scraper .
  docker tag scraper:latest 919759177803.dkr.ecr.us-east-1.amazonaws.com/scraper:latest
  docker push 919759177803.dkr.ecr.us-east-1.amazonaws.com/scraper:latest