build:
  docker build -t scraper .

run: build
  docker run \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
  --env-file ./.env \
  -p 9000:8080 \
  --rm \
  scraper