build:
  docker build -t screenshot:latest .

run: build
  # Make sure you ran awsume for your account
  docker run \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
  -e AWS_LAMBDA_FUNCTION_TIMEOUT=900 \
  -p 9000:8080 \
  --rm --name screenshot \
  screenshot:latest

test:
  curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" \
  -d '{ "queryStringParameters": { "map": "fallout", "uuid": "0195ab1b-46ac-7ab3-a617-f632417e1cda", "z": "5.5" } }'

clean:
  docker rm screenshot
