build:
  docker build -t discord .

run: build
  docker run \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
  -e AWS_LAMBDA_FUNCTION_TIMEOUT=900 \
  --env-file ./.env \
  -p 9000:8080 \
  --rm --name discord \
  discord

test:
  curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d "{}"