build:
  docker build -t discord .

run: build
  docker run \
  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-''} \
  --env-file ./.env \
  --rm \
  discord

upload:
  aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 919759177803.dkr.ecr.us-east-1.amazonaws.com
  docker build -t discord .
  docker tag discord:latest 919759177803.dkr.ecr.us-east-1.amazonaws.com/discord:latest
  docker push 919759177803.dkr.ecr.us-east-1.amazonaws.com/discord:latest